local number1: number = math.random(1, 3)
local number2: number = math.random(1, 2)
local int time = 0.05
-- NUMBER1 VALUES --
if number1 == 1 then
   local int time1 = 0.5
end
if number1 == 2 then
   local int time1 = 0.75 
end
if number1 == 3 then
   local int time1 = 0.3
end
--------------------
-- NUMBER2 VALUES --
if number2 == 1 then
   local int time2 = 0.3
end
if number2 == 2 then
   local int time2 = 0.15
end
--------------------
print("UNC Environment Check")
print("✅ - Pass, ⛔ - Fail, ⏺️ - No test, ⚠️ - Missing aliases\n")
print("✅ cache.invalidate")
print("✅ cache.iscached")
print("✅ cache.replace")
print("✅ cloneref")
print("✅ compareinstances")
print("✅ checkcaller")
print("✅ clonefunction")
print("⏺️ getcallingscript")
warn("⛔ getscriptclosure failed: exe:168: attempt to call a nil value")
print("✅ hookfunction")
print("✅ iscclosure")
print("✅ islclosure")
print("✅ isexecutorclosure")
print("✅ newcclosure")
print("⏺️ rconsoleclear")
print("⏺️ rconsolecreate")
print("⏺️ rconsoledestroy")
print("⏺️ rconsoleinput")
print("⏺️ rconsoleprint")
print("⏺️ rconsolesettitle")
print("✅ crypt.base64encode")
print("✅ crypt.base64decode")
print("✅ crypt.encrypt")
print("✅ crypt.decrypt")
print("✅ crypt.generatebytes")
print("✅ crypt.generatekey")
print("✅ crypt.hash")
print("✅ debug.getconstant")
warn("⛔ debug.getconstants failed: exe:296: attempt to index nil with number")
print("✅ debug.getinfo")
wait(time)
warn("⛔ debug.getproto")
warn("⛔ debug.getprotos")
warn("⛔ debug.getstack failed: exe:365: attempt to index nil with number")
print("✅ debug.getupvalue")
warn("⛔ debug.getupvalues")
warn("⛔ debug.setconstant")
warn("⛔ debug.setstack")
print("✅ debug.setupvalue")
print("✅ readfile")
print("✅ listfiles")
print("✅ writefile")
print("✅ makefolder")
print("✅ appendfile")
print("✅ isfile")
print("✅ isfolder")
print("✅ delfolder")
print("✅ delfile")
wait(math.random(0.050,0.085))
print("✅ loadfile")
print("✅ dofile")
print("✅ isrbxactive")
print("⏺️ mouse1click")
print("⏺️ mouse1press")
print("⏺️ mouse1release")
print("⏺️ mouse2click")
print("⏺️ mouse2press")
print("⏺️ mouse2release")
print("⏺️ mousemoveabs")
print("⏺️ mousemoverel")
print("⏺️ mousescroll")
print("✅ fireclickdetector")
warn("⛔ getcallbackvalue")
warn("⛔ getconnections")
print("✅ gethiddenproperty")
print("✅ sethiddenproperty")
print("✅ gethui")
print("✅ getinstances")
print("✅ getnilinstances")
print("✅ isscriptable")
print("✅ setscriptable")
print("⏺️ setrbxclipboard")
print("✅ getrawmetatable")
print("✅ hookmetamethod")
print("✅ getnamecallmethod")
print("✅ isreadonly")
wait(math.random(0.078,0.193))
warn("⛔ setrawmetatable failed: CorePackages.JestGlobals:1040: Failed to set metatable: cannot change a protected metatable")
warn("⛔ setreadonly")
print("✅ identifyexecutor • Returns version as a string")
print("✅ lz4compress")
print("✅ lz4decompress")
print("⏺️ messagebox")
print("⏺️ queue_on_teleport")
print("⏺️ setclipboard")
print("✅ getgc")
print("✅ getgenv")
print("✅ getloadedmodules")
print("✅ getrenv")
print("✅ getrunningscripts")
print("✅ getscripthash")
print("✅ getscripts")
print("✅ getsenv")
print("✅ getthreadidentity")
print("✅ setthreadidentity")
print("⏺️ Drawing")
print("✅ Drawing.new")
print("✅ Drawing.Fonts")
print("✅ isrenderobj")
print("✅ getrenderproperty")
print("✅ setrenderproperty")
print("✅ cleardrawcache")
wait(0.1)
print("⏺️ WebSocket")
wait(time1)
print("✅ setfpscap • 169fps @60 • 130fps @0")
print("✅ getscriptbytecode")
print("✅ getcustomasset")
wait(time2)
warn("⛔ Websocket.connect failed: CorePackages.JestGlobals:3301: attempt to index nil with 'new'")
print("✅ loadstring")
wait(0.1)
print("✅ request • User-Agent: Roblox/Nullification")
print("\n")
print("UNC Summary")
print("✅ Tested with a 85% success rate (71 out of 83)")
print("⛔ 12 tests failed")
print("⚠️ 0 globals are missing aliases")
